### ISSUE TITLE
Compile ES6/ES2015 version

### ISSUE THREAD

**Issue by andykenward** [Stinkstudios/sono#10]
Would be great to compile a ES6 version of the library for use in a project.

Which should allow for tree-shaking.

Should this be defined in the [rollup.config.js](https://github.com/Stinkdigital/sono/blob/5b762652cfdff4e9f5a3b3ba5c4def001bf8e0a2/rollup.config.js)?
Rollup reference
[How to Build and Publish ES6 Modules Today, with Babel and Rollup](https://medium.com/@tarkus/how-to-build-and-publish-es6-modules-today-with-babel-and-rollup-4426d9c7ca71#.hjxlzor0s)

I've  done this as a npm script in the `package.json` using babel cli before.

```
"build:commonjs": "BABEL_ENV=commonjs babel src --out-dir lib",
"build:es": "BABEL_ENV=es babel src --out-dir es",
```

Then in either a `.babelrc` config file or the `package.json` you define the `env`

```
{
  "presets": [
    "latest", {
      "es2015": {
        "modules": false
      }
    }
  ],
  "env": {
    "commonjs": {
      "plugins": [
        [
          "transform-es2015-modules-commonjs",
          {
            "loose": true
          }
        ]
      ]
    },
    "es": {
      "plugins": [
        "./build/use-lodash-es"
      ]
    }
  }
}

```

**Comment by ianmcgregor** [comment]
Hey @andykenward it looks like it's a case of setting the format as `es6` instead of `umd` in `rollup.config.js`: https://github.com/Stinkdigital/sono/blob/master/rollup.config.js#L11. We could pass in another `process.env` value for that.

I also think we need to look at moving the effects and waveform utils into separate modules to make the tree shaking work effectively.
